"""empty message

Revision ID: 83186cd81246
Revises: f8c95d6f2ae3
Create Date: 2022-12-19 14:03:52.895205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83186cd81246'
down_revision = 'f8c95d6f2ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('sifre', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kullanici')
    # ### end Alembic commands ###
